---
- name: install dependencies in CentOS
  become: yes
  yum: name={{item}} state=latest
  with_items:
    - gcc
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
  when: ansible_os_family == 'RedHat'

- name: install dependencies in Debian family
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
  when: ansible_os_family == 'Debian'

- name: install rbenv
  become: yes
  git: repo=https://github.com/sstephenson/rbenv.git dest={{rbenv_root}}

- name: install ruby-build
  become: yes
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{rbenv_root}}/plugins/ruby-build

- name: make rbenv group
  become: yes
  group: name=rbenv

- name: set rbenv env file
  become: yes
  template: >
    src=rbenv.sh.j2
    dest=/etc/profile.d/rbenv.sh
    mode=664
    group=rbenv

- name: change attributes of {{rbenv_root}}
  become: yes
  file: >
    path={{rbenv_root}}
    mode=g+rwXs
    group=rbenv
    state=directory
    recurse=yes

- name: add user to rbenv group
  become: yes
  user: name={{rbenv_user}} append=yes groups=rbenv
